### PR TITLE
Adds a new, dynamic, report page

### PR DESCRIPTION
**Pull request by yscialom**
Hi!
I'd like you to test this commit and to give me some feedback.

"This huge commit reworks the way the jobs offers are displayed to the user.
The new report offers some excitting new features:
    - dynamic column sorting;
    - dynamic column search:
        - the publication date can be search with the help of
            a calendar (it's pretty :);
        - the company type, the company name, the contract type
            and the offer source can be selected from a dropdown
            menu;
        - a dynamic text search can be made on the job title;
        - the job location can be filtered from an address (or just
            a city name) and a range;
        - the job salary can be filtered with a top and bottom boundary."

### CODE REVIEW

**Comment by yscialom** [comment]
Note that this feature is still in development phase. It is not to be merged into your master branch.

**Comment by yoannsculo** [comment]
Wow ! Nice ! Thanks, this is exactly was we needed !!

I have indeed some feedback. I have collected 6481 offers on my database. Usually it takes a while (some seconds) to load the entire page. With the javascript firefox tells me the jquery scripts are not responding. I don't know how we could solve this. Either we use a paging system or we find a other way to lighten the page. If you want I can send you my database.

I think you should embed all javascript code into the project and not hotlink it.

I love the dynamic filtering by Company, even if it takes some long seconds to display the result.

The salary filtering just blocked the page once I tried to play with the cursor :/

For the location column I guess it would be better to use a config parameter. I suppose the research should not be a value that changes so much.

I love the whole dynamic sorting too !

The calendar is very hard to use with my amount of offers. And I think we should find a way to decrease the width of this colum. Maybe if we only use a calendar button with the texarea and button in a popup.

An other point would be to put a separator between days, like the current master report page.

Nice work !!!

**Comment by yscialom** [comment]
There is a lot to say and do about the dynamic report. I'll treat it point by point (which later will be features and branches ;).

"I have collected 6481 offers on my database. Usually it takes a while (some seconds) to load the entire page. With the javascript firefox tells me the jquery scripts are not responding. I don't know how we could solve this. Either we use a paging system or we find a other way to lighten the page. If you want I can send you my database".
As of the final aim of JobCatcher is to display _fresh_ job offers to the user, a database as big as 6481 entries seems a bit overkill. Don't we want to automatically delete old offers (say, older that two monthes)? In addition to that, i'm willing to add a dynamic pagination system. I'm happy to know thhough that my code isn't working properly for big reports; i'll work on that.

"I think you should embed all javascript code into the project and not hotlink it."
Absolutly. I'll also purify the jquery and jquery-ui to get only what is needed.

"I love the dynamic filtering by Company, even if it takes some long seconds to display the result."
Good to know. Do you think a text box should replace the dropbox menu?

"The salary filtering just blocked the page once I tried to play with the cursor :/"
Same problem here. For small report it works pretty well.

"For the location column I guess it would be better to use a config parameter. I suppose the research should not be a value that changes so much."
As a matter of fact, for small (~50) entries, the text box plus slider work pretty well. Though, the last used distance range should be kept as a config parameter.

"The calendar is very hard to use with my amount of offers."
Why is that?

"And I think we should find a way to decrease the width of this colum. Maybe if we only use a calendar button with the texarea and button in a popup."
Yes. The whole css is to be done. I'd like to merge the refresh/reset buttons into the text bars (to get something like this http://www.textfixer.com/tutorials/html-search-box.php).
I'm not sure to get what you mean about the calendar though :/.

To conclude :
- [x] Add a dynamic pagination system (issue #9)
- [x] Profile and optimize the javascript code (issue #10)
- [x] Embed the jquery[-ui] into the project (issue #11)
- [x] Store the distance range as a configuration parameter (issue #12)
- [x] Put a CSS dress&makeup onto all that (issue #13)

**Comment by yoannsculo** [comment]
Actually, there are two purposes for Jobcatcher :
- display the last offers
- store all the offers to generate reports, statistics and graphics to
  visualize information such as trends, salary evolution, amount of offers,
  etc. The idea is to discover when it's a good moment to change jobs for a
  specific sector for example. But mainly to generate interesting reports
  from those "old" data.

For the first element, we need to decide what is a fresh offer and what's
its validity.

Either we see JobCatcher as a rss feed reader. So the user needs to
regularly parse it to detect interesting offers. But offers won't be
displayed after N weeks/months for instance. Just fresh data.
Or we can consider it more like a BIG job board where the user can search
for terms in offers like 4 or 5 months old. Those offers can still be
valid. For example, I've been employed for an 1.5 year old offer this year.

For me, we should try to find a common ground. To allow the user to put a
cursor for the validity he wants. Unfortunately, it causes issues with the
amount of data fetched by the software. And the spirit of JobCatcher is to
use static html pages too. So it won't be easy, but let's find way !

Did you see other changes made on the project by Bruno ?
https://github.com/badele/JobCatcher I added him to the project, I can add
you too. It will ease pull requests since you can push directly into the
project.

"Good to know. Do you think a text box should replace the dropbox menu?"
I think it's perfect like this !

"The calendar is very hard to use with my amount of offers."
Why is that?

It takes looooong seconds to filter all the offers I have. Thus one click
on the calendar freezes the page for a while.

For the calendar, I mean size of the column (width) is defined by the size
of the top row. We waste some space using a big field that could appear on
an external js popop for example, and not directly into the first table row.

I agree with you with the Todolist. For the dynamic pagination system I
think we should further discuss that point and all other ones by email in
French :P It should be quicker ^^

**Comment by yscialom** [comment]
Ok, let's discuss each opened issue in french and put a report in english in the corresponding issue.

**Pull request closed without merging**
